# Site settings
title: Alejandro Babio
email: alejandroebabio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alejandrobabio.github.io" # the base hostname & protocol for your site
twitter_username: alejandro_babio
github_username:  alejandrobabio
stackoverflow_profile: "4151953/alejandro-babio?tab=profile"
google_plus_profile: 108533475599002820142
linkedin_profile: "alejandro-babio/11/537/a7"
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
plugins: [jekyll-coffeescript]
