# Site settings
title: Alejandro Babio
email: alejandroebabio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alejandrobabio.github.com" # the base hostname & protocol for your site
twitter_username: alejandro_babio
github_username:  alejandrobabio

# Build settings
markdown: kramdown
